all_coaches_url: https://www.dropbox.com/s/xus9dhoytlhofqs/all_coaches.csv?dl=1
all_matches_url: https://www.dropbox.com/s/t8cq8zixe99fl8f/all_matches.csv?dl=1
mu: 1500
phi: 500
tau: 0.2
sigma: 0.06
phi_penalty: 3
phi_limit: 250
phi_active: 250
update_freq: '2W'
global_mode: True
global_excl: ['Goblins', 'Halflings', 'Ogres', 'Underworld']
extra_cols: ['phi', 'decay', 'change', 'qrank', 'old_rank', 'qrace_rank', 'old_race_rank', 'rank_change']
cutoff: today
time_period: "5y"
