mu: 1500
phi: 350
tau: 0.2
sigma: 0.06
phi_penalty: 2.5
phi_limit: 250
phi_active: 100
global_mode: False
global_excl: []
update_freq: '1M'
extra_cols: ['phi', 'decay', 'change', 'qrank', 'old_rank', 'qrace_rank', 'old_race_rank', 'rank_change']
cutoff: today
